language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t teejosh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true teejosh/docker-react npm run test